name: Atualização das versões dos pacotes do repositório
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # rodar todo dia as 3 da matina quando não tem ninguém nexendo (eu espero) (6-3 = 3 da manhã, hora é no fuso GMT)
jobs:
  bump:
    name: Realizar o bump automático dos paranaue
    runs-on: ubuntu-latest
    steps:
    - name: Puxar o código
      uses: actions/checkout@v1
    - name: Rodar o script de bump
      run: ./atualizar
    - name: Quem sou eu?
      run: |
        git config --global user.email bot@skynet.org
        git config --global user.name "Bot do repositório"
    - name: A parte que o Git cuida
      run: |
        if [ ! -z "$(git diff)" ]; then
          git add -A && git commit -m "bump" && git push origin ${{ github.ref }}
        else
          echo "Nada a alterar"
        fi
    - name: Ver que é só isso
      run: echo É só isso
